googleapis/langchain-google-bigtable-python

docs/document_loader.ipynb, src/langchain_google_bigtable/document_loader.py, src/test/test_document_loader.py
=> feat: Metadata as json

docs/chat_message_history.ipynb
=> docs: Update chat_message_history.ipynb

docs/document_loader.ipynb
Add in documentation to import documentloader
=> docs: Update document_loader.ipynb

docs/chat_message_history.ipynb, docs/document_loader.ipynb
=> docs: add github links and doc fixes

.github/sync-repo-settings.yaml, DEVELOPER.md, integration.cloudbuild.yaml, src/langchain_google_bigtable/loader.py
=> feat(ci): test against multiple versions

pyproject.toml, src/langchain_google_bigtable/common.py
=> fix: update user agent

.kokoro/requirements.txt
=> chore(ci): update kokoro dependencies

.github/CODEOWNERS, .github/sync-repo-settings.yaml
=> chore: update owner

.github/blunderbuss.yml, .github/header-checker-lint.yml
Add blunderbuss to auto assign issues and prs
=> ci: Add blunderbuss config

.coveragerc, DEVELOPER.md, integration.cloudbuild.yaml, pyproject.toml
Add code coverage check as part of running test suite. Test suite will fail with coverage below 90%.
=> ci: Add code coverage check

tests/test_bigtable_loader.py
It seems 10 seconds are not enough time to wait for eventual consistency.
Fixes #59  🦕
=> fix: Increase delay in test

tests/test_bigtable_chat_message_history.py
=> fix: Increase delay in test 

src/langchain_google_bigtable/chat_message_history.py, src/langchain_google_bigtable/loader.py
=> fix: Add return type annotation where missing

pyproject.toml
disallow incomplete input and return types
=> ci: Add mypy function type check

src/langchain_google_bigtable/chat_message_history.py, tests/test_bigtable_chat_message_history.py, tests/test_bigtable_loader.py
=> fix: fixed issue with messages history tests

src/langchain_google_bigtable/chat_message_history.py, tests/test_bigtable_chat_message_history.py
=> chore(tests): Implement add_messages to allow a more efficient loading for lots of messages

pyproject.toml, requirements.txt, src/langchain_google_bigtable/loader.py
=> feat: remove dependency on langchain-community

docs/chat_message_history.ipynb, pyproject.toml, requirements.txt, src/langchain_google_bigtable/__init__.py, src/langchain_google_bigtable/chat_message_history.py, tests/test_bigtable_chat_message_history.py
=> feat: add init_chat_history_table function

src/langchain_google_bigtable/chat_message_history.py, src/langchain_google_bigtable/loader.py
=> feat: add comments to all exported functions

docs/chat_message_history.ipynb, docs/document_loader.ipynb
=> feat: Updated docs for recently added features

DEVELOPER.md
=> docs: Update playbook to explain tests quota issue

.github/sync-repo-settings.yaml, DEVELOPER.md, README.rst, integration.cloudbuild.yaml, pyproject.toml
=> feat: remove support for Python 3.8

.github/workflows/docs.yml
chore: update gh workflow permissions
=> chore: update gh workflow permissions

src/langchain_google_bigtable/engine.py, tests/test_engine.py
=> feat: add BigtableEngine Class for managing the client and execution context
